/*
 Navicat Premium Data Transfer

 Source Server         : Test
 Source Server Type    : PostgreSQL
 Source Server Version : 130002
 Source Host           : localhost:5432
 Source Catalog        : Falabella
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130002
 File Encoding         : 65001

 Date: 14/08/2021 12:46:15
*/


-- ----------------------------
-- Sequence structure for cliente_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."cliente_id_seq";
CREATE SEQUENCE "public"."cliente_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for cuenta_numero_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."cuenta_numero_seq";
CREATE SEQUENCE "public"."cuenta_numero_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for nota_credito_debito_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."nota_credito_debito_id_seq";
CREATE SEQUENCE "public"."nota_credito_debito_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for cliente
-- ----------------------------
DROP TABLE IF EXISTS "public"."cliente";
CREATE TABLE "public"."cliente" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "nombre" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "apellido" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "tipo_documento" int2 NOT NULL,
  "numero_documento" varchar(15) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of cliente
-- ----------------------------
INSERT INTO "public"."cliente" VALUES (1, 'A', 'A', 0, '000000');
INSERT INTO "public"."cliente" VALUES (2, 'B', 'B', 0, '111111');
INSERT INTO "public"."cliente" VALUES (3, 'C', 'C', 1, '22222');

-- ----------------------------
-- Table structure for contacto
-- ----------------------------
DROP TABLE IF EXISTS "public"."contacto";
CREATE TABLE "public"."contacto" (
  "id_cliente" int4 NOT NULL,
  "tipo_contacto" int2 NOT NULL,
  "valor" varchar(100) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of contacto
-- ----------------------------
INSERT INTO "public"."contacto" VALUES (1, 1, 'AAA');
INSERT INTO "public"."contacto" VALUES (2, 1, 'BBB');
INSERT INTO "public"."contacto" VALUES (3, 1, 'CCC');

-- ----------------------------
-- Table structure for cuenta
-- ----------------------------
DROP TABLE IF EXISTS "public"."cuenta";
CREATE TABLE "public"."cuenta" (
  "numero" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "tipo_cuenta" int2 NOT NULL,
  "credito_limite" numeric(20,2) NOT NULL,
  "fecha_apertura" date NOT NULL,
  "estado" int2 NOT NULL,
  "id_cliente" int4 NOT NULL
)
;

-- ----------------------------
-- Records of cuenta
-- ----------------------------
INSERT INTO "public"."cuenta" VALUES (3, 1, 300000.00, '2021-02-13', 0, 3);
INSERT INTO "public"."cuenta" VALUES (5, 1, 100000.00, '2004-07-27', 0, 1);
INSERT INTO "public"."cuenta" VALUES (2, 0, 200000.00, '2021-08-13', 0, 2);
INSERT INTO "public"."cuenta" VALUES (1, 1, 100000.00, '2020-08-13', 0, 1);

-- ----------------------------
-- Table structure for nota_credito_debito
-- ----------------------------
DROP TABLE IF EXISTS "public"."nota_credito_debito";
CREATE TABLE "public"."nota_credito_debito" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "numero_cuenta" int4 NOT NULL,
  "es_nota_credito" int2 NOT NULL,
  "fecha_registro" date NOT NULL,
  "valor" numeric(20,2) NOT NULL
)
;

-- ----------------------------
-- Records of nota_credito_debito
-- ----------------------------
INSERT INTO "public"."nota_credito_debito" VALUES (2, 1, 0, '2021-08-18', 5000000.00);
INSERT INTO "public"."nota_credito_debito" VALUES (1, 1, 1, '2021-08-14', 200000.00);


-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."cliente_id_seq"
OWNED BY "public"."cliente"."id";
SELECT setval('"public"."cliente_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."cuenta_numero_seq"
OWNED BY "public"."cuenta"."numero";
SELECT setval('"public"."cuenta_numero_seq"', 6, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."nota_credito_debito_id_seq"
OWNED BY "public"."nota_credito_debito"."id";
SELECT setval('"public"."nota_credito_debito_id_seq"', 3, true);

-- ----------------------------
-- Primary Key structure for table cliente
-- ----------------------------
ALTER TABLE "public"."cliente" ADD CONSTRAINT "cliente_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table contacto
-- ----------------------------
ALTER TABLE "public"."contacto" ADD CONSTRAINT "contacto_pkey" PRIMARY KEY ("id_cliente");

-- ----------------------------
-- Primary Key structure for table cuenta
-- ----------------------------
ALTER TABLE "public"."cuenta" ADD CONSTRAINT "cuenta_pkey" PRIMARY KEY ("numero");

-- ----------------------------
-- Primary Key structure for table nota_credito_debito
-- ----------------------------
ALTER TABLE "public"."nota_credito_debito" ADD CONSTRAINT "nota_credito_debito_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table contacto
-- ----------------------------
ALTER TABLE "public"."contacto" ADD CONSTRAINT "fk_contacto_cliente_1" FOREIGN KEY ("id_cliente") REFERENCES "public"."cliente" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table cuenta
-- ----------------------------
ALTER TABLE "public"."cuenta" ADD CONSTRAINT "fk_cuenta_cliente_1" FOREIGN KEY ("id_cliente") REFERENCES "public"."cliente" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table nota_credito_debito
-- ----------------------------
ALTER TABLE "public"."nota_credito_debito" ADD CONSTRAINT "fk_nota_credito_debito_cuenta_1" FOREIGN KEY ("numero_cuenta") REFERENCES "public"."cuenta" ("numero") ON DELETE NO ACTION ON UPDATE NO ACTION;
